#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : azure-configs
Version  : 1.0.0
Release  : 11
URL      : https://127.0.0.1/clearlinux-pkgs/azure-configs/blob/master/azure-configs-dev-1.0.0.tar.gz
Source0  : https://127.0.0.1/clearlinux-pkgs/azure-configs/blob/master/azure-configs-dev-1.0.0.tar.gz
Source1  : fcopy.service
Source2  : kvp.service
Source3  : vss.service
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: azure-configs-autostart = %{version}-%{release}
Requires: azure-configs-config = %{version}-%{release}
Requires: azure-configs-libexec = %{version}-%{release}
Requires: azure-configs-services = %{version}-%{release}

%description
No detailed description available

%package autostart
Summary: autostart components for the azure-configs package.
Group: Default

%description autostart
autostart components for the azure-configs package.


%package config
Summary: config components for the azure-configs package.
Group: Default

%description config
config components for the azure-configs package.


%package libexec
Summary: libexec components for the azure-configs package.
Group: Default
Requires: azure-configs-config = %{version}-%{release}

%description libexec
libexec components for the azure-configs package.


%package services
Summary: services components for the azure-configs package.
Group: Systemd services

%description services
services components for the azure-configs package.


%prep
%setup -q -n azure-configs-1.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1544216637
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1544216637
rm -rf %{buildroot}
%make_install
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/fcopy.service
install -m 0644 %{SOURCE2} %{buildroot}/usr/lib/systemd/system/kvp.service
install -m 0644 %{SOURCE3} %{buildroot}/usr/lib/systemd/system/vss.service
## install_append content
mkdir -p %{buildroot}/usr/lib/systemd/system/multi-user.target.wants
ln -s ../kvp.service %{buildroot}/usr/lib/systemd/system/multi-user.target.wants/
ln -s ../vss.service %{buildroot}/usr/lib/systemd/system/multi-user.target.wants/
mkdir -p %{buildroot}/usr/libexec/hypervkvpd
install -m 0755 hv_get_dhcp_info %{buildroot}/usr/libexec/hypervkvpd/hv_get_dhcp_info
install -m 0755 hv_get_dns_info %{buildroot}/usr/libexec/hypervkvpd/hv_get_dns_info
install -m 0755 hv_set_ifconfig %{buildroot}/usr/libexec/hypervkvpd/hv_set_ifconfig
## install_append end

%files
%defattr(-,root,root,-)

%files autostart
%defattr(-,root,root,-)
/usr/lib/systemd/system/multi-user.target.wants/kvp.service
/usr/lib/systemd/system/multi-user.target.wants/vss.service

%files config
%defattr(-,root,root,-)
/usr/lib/udev/rules.d/99-balloon.rules

%files libexec
%defattr(-,root,root,-)
/usr/libexec/hypervkvpd/hv_get_dhcp_info
/usr/libexec/hypervkvpd/hv_get_dns_info
/usr/libexec/hypervkvpd/hv_set_ifconfig

%files services
%defattr(-,root,root,-)
%exclude /usr/lib/systemd/system/multi-user.target.wants/kvp.service
%exclude /usr/lib/systemd/system/multi-user.target.wants/vss.service
/usr/lib/systemd/system/fcopy.service
/usr/lib/systemd/system/kvp.service
/usr/lib/systemd/system/vss.service
